### PR TITLE
Dynamic BookEntries

### PR DESCRIPTION
**Pull request by DaFuqs**
## What is this?
This PR aims to split the `BookEntry` class into a base `abstract BookEntry` class with `ContentBookEntry` (contains pages) and `CategoryLinkBookEntry` (opens other categories; like the previous `category_to_open` in all entries) as children. Similar to pages which are expandable by other mods, `LoaderRegistry` now contains a mapping for book entry types, with the two defaults `EntryType.CONTENT` and `EntryType.CATEGORY_LINK`.

The new json parsing mechanism [uses a fallback](https://github.com/klikli-dev/modonomicon/compare/version/1.20.1...DaFuqs:version/1.20.1-modular-bookentries?expand=1#diff-d4491910158ab3eee483b5dd1c0ed63a9f793cff23ca770b40e761a52f9aeceeR200), which makes existing books work exactly as they did before, so nothing breaks.

Posting this as a draft PR to get some feedback on functionality and naming before I redo the datagen and add new features.
Currently functionality is 1:1 as before, just with updated internals.

## Why?
Spectrum's guidebook is huge. For ease of use for the player, some crucial entries benefit from being accessible from 2+ categories.
I plan to achive this by having an additonal `EntryType.ENTRY_LINK`, which opens an other entry on click. Basically holding a reference to an other entry from another chapter which the player is transferred to.

Since `openEntry()` is now implemented in the entry itself, I can also see the new system being used for other stuff entirely, like entries which do not have any content whatsoever, but only execute a command on click, for example.

## What is left to do?
- ~~Updating and re-running datagen~~ 100% backwards compatible!
- ~~Updating the wiki~~ 100% backwards compatible! Mods that want to add new entry types will benefit from an updated doc, though
- ~~Adding `EntryType.ENTRY_LINK`~~ I will test that separately and create a PR for that later

~~One part of the code is still a bit ugly. `fromJson()` and `fromNetwork()` use lots of duplicate code. This could be improved by moving the common properties of BookEntries into a holder class, which can easily be serialized / deserialized in a single swoop. But I would like some feedback on that before I make even more big changes.~~ DONE

### CODE REVIEW

**Comment by klikli-dev** [comment]
I like the refactor, it makes sense especially in light of your future plans for an additional entry type and the general extensibility.
The implementation looks good - just one note on the parsing: It may be good to move the parsing of common properties into the base class. 
We could use a record to hold them. That way if at any point the base properties of the entry change we reduce friction in updating the parsing code. 
Somewhere in the mod there is an example of that (I think maybe pages?). Not sure if it is super clean code, so I am open to discussing how to best do that

**Comment by DaFuqs** [comment]
I added `BookEntryData` record, which holds all the "raw" information and can be easily de/serialized, so the code is much more concise.
I tinkered with having that record split into multiple records (for position, lang data, ...), but there really wasn't a need to.

I tested with the demo book entry and everything worked out of the box, without any changes to the json files, so everything is backwards compatible

**Comment by DaFuqs** [comment]
Datagen could get updated to use the new `BookEntryData` class, but the current one works fine. I left it as-is for now, so mods do not need to update their code.

**Comment by klikli-dev** [comment]
Looks good, thanks a lot!
Do you want to make any further changes or is it ready for merge?

**Comment by DaFuqs** [comment]
Finished by me, thanks!
I will try around in my own mod by adding new entry types and if I find any that seem useful for other mods I will PR them separately

**Pull request merged**
