### PR TITLE
Various improvements around entry unlocks

### PR DESCRIPTION
**Pull request by DaFuqs**
This PR has 3 commits (well, plus a [small nitpick one](https://github.com/klikli-dev/modonomicon/commit/59eee68331976915f152850322e64b54bdada91d)).
Also I noticed too late that I messed up your wildcard imports, sorry!

## [1. make entries show up if their unlock condition is met regardless of their parent unlocks](https://github.com/klikli-dev/modonomicon/commit/8e094ee25c5b68e7dcdac36f0019916dcb3b359c) 

Entries that do not have parents now get rendered when their unlock condition is met, regardless of their parents.
This fixes an inconsistency where entries that had their unlock met, but not any/all parents unlocked, would show up in the search, but not on the actual category pages.

## [2. special handling for entries without parents](https://github.com/klikli-dev/modonomicon/commit/af942bad36df9927cd1edae84ef592d74e4bbe67)

This fixes some oversights when an entry did not have any parents
- `anyParentsUnlocked` would always be false when an entry does not have any parents
- `isEntryUnlocked (condition met)` would be ignored unless at least one/all parents are unlocked, creating an inconsistency where they would show up in the index, but not in the categories

## [3. BookCategoryHasEntriesCondition => BookCategoryHas*Visible*EntriesCondition](https://github.com/klikli-dev/modonomicon/commit/1acf6cd85319f72f5363ccc736cc1c6b3f4ead60) 

Renames the `BookCategoryHasEntriesCondition` to `BookCategoryHasVisibleEntriesCondition`. This is a small breaking change, but since the condition is not yet documented in the docs I assume it is not getting used much yet.

To reuse existing code I moved `getEntryDisplayState` from `BookCategoryScreen` to `BookEntry`, but it is functionally the same. For ease of use `EntryDisplayState` now can be queried for `isVisible()` (locked, unlocked) and `isUnlocked()` (unlocked).

> Why rename it and not add a second?

Cause the functionality of the changed version is functionally backwards compatible with the previous one (minus the id renaming, that is). The condition
```json
"condition": {
  "type": "modonomicon:category_has_visible_entries",
  "category_id": "spectrum:equipment"
}
```
will evaluate to true if the category has any entries that are visible (locked & unlocked, not hidden), or if the category has no entries at all. I feel that is implicitly reflected in the naming pretty nicely.

### CODE REVIEW

**Comment by DaFuqs** [comment]
I also found that some parts of the code use `(this.bookOverviewScreen.getMinecraft().player` and some `Minecraft.getInstance().player`, but I did not touch those. Maybe you had a good reason for that?

**Comment by klikli-dev** [comment]
@DaFuqs thank you so much!
Regarding the .player: that was not an intentional discrepancy. It should be fine to use either.

Regarding the breaking change: This feature was either added by someone, or requested by someone, so I need to track them down and see how it would affect them before merging. 

Regarding the parent changes: I think these are all good to go!

**Comment by klikli-dev** [comment]
Oh wait, I think the person adding it was you ..

**Comment by DaFuqs** [comment]
Yeah, pretty sure I added it for my category of mod compat entries, which could be empty when no mod with compat was loaded, thus the category being completely empty.
This new variant catches that case too, so we fine. Ty!

**Pull request merged**
